language: node_js
node_js:
  - "node"

before_install:
  - npm install

script:
  - NODE_ENV=production npm run build
<<<<<<< HEAD
  - echo "Checking build"
=======
  - echo "skipping tests"
>>>>>>> master

cache:
   directories:
     - node_modules
